; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Global override to the shared directory
; Uncomment src_dir = ./src
;src_dir = ./src_blinkTest
src_dir = ./src_DFO

[env:attiny13a]
platform = atmelavr
board = attiny13a
framework = arduino
board_build.f_cpu = 9600000L
board_fuses.lfuse = 0x7A
;board_fuses.lfuse = 0x6A
;board_fuses.hfuse = 0xFF - dont mess with is, it may turn off isp(RESET pin PB5)
upload_protocol = usbasp

; Force a slow SCK clock (safe for brand-new chips)
;upload_flags =
;    -c usbasp
;    -p t13
;    -B 32   ; Sets a very slow SCK bit clock period (approx. 32kHz)
;    -U lfuse:w:0x6A:m

;build_src_filter = -<*> +<main.cpp> +<i2cmaster.h> +<i2cmaster.S>

; -=[ Crucial Step ]=-
; If attiny13 is brand new:
;   1. The new attiny13 runs at 1.2Mhz: You need to slow down the usbasp programmer by the jumper(JP3) on the PCB
;   2. Run this command "pio run -t fuses" in your PlatformIO terminal to set attiny13 to 9.6MHz frequency
;   3. Put the jumper(JP3) to it's default position on usbasp programmer
;   4. Now you can flesh your code to the attinyIn13 at high speed

; -=[ About fuse settings ]=-
; Custom fuse settings https://community.platformio.org/uploads/default/original/2X/8/8f7fccdb7085d2b826c50c93966231b27957ddc4.png
; board_fuses.lfuse = 0x6A ;Low Fuse: 0x6A (1.2MHz internal oscillator, enabled CKDIV8).
; board_fuses.lfuse = 0x7A ;Low Fuse: 0x7A (9.6MHz internal oscillator, disabed CKDIV8).
; board_fuses.hfuse = 0xFF ;High Fuse: 0xFF (Default for ATtiny13) DO NOT MESS WITH IT! before learning what it is.
; The factory default fuses for a brand-new ATtiny13 are: lfuse = 0x6A      and hfuse = 0xFF 1.2 MHz
;                                                                 0x6A 0b01101010       0xFF 1.2 MHz
;                                                                 0x2A 0b00101010
;                                                                 0x7A 0b01111010       0xFF 9.6 MHz

; other useful info
;###############################################################
;attiny13int.name=Attiny13 @ 128 KHz (internal watchdog oscillator)
;attiny13int.upload.using=arduino:arduinoisp
;attiny13int.upload.maximum_size=1024
;attiny13int.upload.speed=250 # important for not losing connection to a slow processor
;attiny13int.bootloader.low_fuses=0x7B
;attiny13int.bootloader.high_fuses=0xFF
;attiny13int.bootloader.unlock_bits=0x3F
;attiny13int.bootloader.lock_bits=0x3F
;attiny13int.build.mcu=attiny13
;attiny13int.build.f_cpu=128000
;attiny13int.build.core=core13

;###############################################################

;attiny13at4.name=ATtiny13 @ 4.8MHz (internal 4.8 MHz clock)
;attiny13at4.upload.using=arduino:arduinoisp
;attiny13at4.bootloader.low_fuses=0x69
;attiny13at4.bootloader.high_fuses=0xff
;attiny13at4.upload.maximum_size=1024
;attiny13at4.build.mcu=attiny13
;attiny13at4.build.f_cpu=600000
;attiny13at4.build.core=core13
###############################################################

;attiny13.name=ATtiny13 @ 9.6MHz (interne 9.6 MHz clock)
;attiny13.upload.using=arduino:arduinoisp
;attiny13.bootloader.low_fuses=0x7a
;attiny13.bootloader.high_fuses=0xff
;attiny13.upload.maximum_size=1024
;attiny13.build.mcu=attiny13
;attiny13.build.f_cpu=1200000
;attiny13.build.core=core13
;###############################################################

; Optional: Ensure flash is erased before setting fuses
;upload_flags = -e

;[env:esp32_app_1]
;platform = espressif32
;board = esp32dev
;framework = arduino
;build_src_filter = +<app_one/> -<app_two/>

;[env:esp32_app_2]
;platform = espressif32
;board = esp32dev
;framework = arduino
;build_src_filter = +<app_two/> -<app_one/>
